                                                          **Theoretical Quetions**

Q 1.Explain the purpose and disadvantages of NumPy in scientific computing and data analysis.How does it enhance Python's capabilities for numerical operations?

Ans:-

NumPy is a core library in Python for scientific computing and data analysis, offering high-performance tools for handling large arrays and matrices. It provides efficient, low-level functions for mathematical operations, enabling researchers and data scientists to perform complex numerical tasks that would be slow or cumbersome with pure Python.

### Purpose of NumPy in Scientific Computing and Data Analysis

1. **Efficient Data Storage**: NumPy arrays (ndarrays) use contiguous memory blocks, allowing for efficient storage and retrieval of large datasets.
2. **Vectorized Operations**: With built-in support for vectorized operations, NumPy allows for element-wise computations without explicit Python loops, significantly speeding up calculations.
3. **Mathematical and Statistical Functions**: NumPy includes a vast array of mathematical, statistical, and algebraic functions, making it easy to perform common operations on data.
4. **Integration with Other Libraries**: NumPy is the foundational library that underpins other scientific libraries like Pandas, SciPy, and TensorFlow, making it essential for data manipulation, statistical analysis, and machine learning.

### Disadvantages of NumPy

1. **Memory Usage**: NumPy’s memory management, while efficient, can still lead to high memory consumption for very large datasets, especially in multi-dimensional arrays.
2. **Lack of Native Support for Multi-core Processing**: While some operations are fast, NumPy doesn’t natively support parallelism or multi-core processing, which can be a limitation when dealing with exceptionally large datasets.
3. **Type Restrictions**: NumPy arrays are homogeneous (all elements must be of the same data type). While this promotes efficiency, it limits flexibility, as you can’t store mixed data types like strings and numbers in the same array.
4. **Limited GPU Support**: NumPy operations typically run on CPU. For machine learning or tasks requiring faster computation, users may need to switch to libraries like CuPy or TensorFlow that leverage GPU acceleration.


- **Performance Boost**: NumPy’s low-level implementation in C makes it much faster than native Python, especially for mathematical operations over large data.
- **Linear Algebra and Random Sampling**: The library includes powerful linear algebra, Fourier transform, and random number generation tools, essential for simulations, statistical models, and more.
- **Broadcasting**: NumPy’s broadcasting mechanism lets arrays of different shapes operate together, simplifying code and avoiding loops.
- **Efficient Aggregations**: Operations like mean, sum, and standard deviation are optimized for performance, which is crucial in data analysis workflows.

In summary, NumPy is a cornerstone for scientific computing in Python, optimizing numerical operations and expanding Python's capabilities. Despite its limitations, its integration with the broader Python data ecosystem makes it invaluable.

Q 2.Compare and contract np.mean() and np.average() function in NumPy.When would you use one over the other?

Ans:-

The `np.mean()` and `np.average()` functions in NumPy both calculate the average of array elements, but they have some differences in functionality and use cases. Here’s a comparison of the two functions:

### `np.mean()`

- **Purpose**: Computes the arithmetic mean along the specified axis or for the entire array if no axis is specified.
- **Parameters**:
  - `axis`: Specifies the axis along which to compute the mean. By default, it computes the mean of all elements.
- **Weighting**: `np.mean()` does **not** support weights; it calculates a simple mean.
- **Return**: Returns a float (if axis is `None`) or an array with the mean values along the specified axis.

### `np.average()`

- **Purpose**: Computes the weighted average of the array, allowing you to specify weights for each element.
- **Parameters**:
  - `axis`: Similar to `np.mean()`, it specifies the axis along which to compute the average.
  - `weights`: An array of the same shape as the input (or broadcastable to the shape) that represents the weight of each element.
- **Weighting**: Unlike `np.mean()`, `np.average()` supports weighting. If no weights are specified, it calculates a simple mean, behaving similarly to `np.mean()`.
- **Return**: Returns a float (if axis is `None`) or an array with the weighted average along the specified axis.

### Key Differences

| Feature                  | `np.mean()`                       | `np.average()`                      |
|--------------------------|-----------------------------------|-------------------------------------|
| **Weighting Support**    | No                               | Yes (via `weights` parameter)       |
| **Default Behavior**     | Arithmetic mean                  | Weighted average (defaults to mean if no weights) |
| **Functionality Focus**  | General purpose mean calculation | Weighted mean, more flexible for specific cases |
| **Return Type**          | Float or array                   | Float or array                      |

### When to Use Each

- **Use `np.mean()`**: When you need a simple average without any weighting. It’s straightforward and generally faster than `np.average()` for basic cases.
  
- **Use `np.average()`**: When the average calculation requires weighting. For example, in scenarios like computing weighted grades or dealing with data where certain elements are more significant, `np.average()` allows you to specify the weight for each element, giving a more representative result.

In short:
- **`np.mean()`**: Use for unweighted arithmetic mean calculations.
- **`np.average()`**: Use when weighting is necessary.


Q 3.Describe the methods for reversing a NumPy array along axex.Provide examples for 1D and 2D arrays.

Ans:-

In NumPy, you can reverse an array along different axes using various methods. Here are the main approaches, along with examples for both 1D and 2D arrays:

1. Using Array Slicing
Slicing with [::-1] reverses an array along a specified axis.

Example for 1D Array

In [ ]:
import numpy as np

# 1D array
arr_1d = np.array([1, 2, 3, 4, 5])
reversed_arr_1d = arr_1d[::-1]
print(reversed_arr_1d)


[5 4 3 2 1]


Example for 2D Array
For a 2D array, [::-1] on rows will reverse the rows, while specifying [:, ::-1] will reverse the columns.

In [ ]:
# 2D array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Reverse rows
reversed_rows = arr_2d[::-1]
print(reversed_rows)




# Reverse columns
reversed_cols = arr_2d[:, ::-1]
print(reversed_cols)



[[7 8 9]
 [4 5 6]
 [1 2 3]]
[[3 2 1]
 [6 5 4]
 [9 8 7]]


2. Using np.flip()
np.flip() provides a convenient way to reverse an array along any specified axis.

Example for 1D Array

In [ ]:
# Flip the 1D array
flipped_arr_1d = np.flip(arr_1d)
print(flipped_arr_1d)


[5 4 3 2 1]


Example for 2D Array

Specify axis=0 for reversing rows and axis=1 for reversing columns.

In [ ]:
# Reverse rows
flipped_rows = np.flip(arr_2d, axis=0)
print(flipped_rows)
# Output:
# [[7 8 9]
#  [4 5 6]
#  [1 2 3]]

# Reverse columns
flipped_cols = np.flip(arr_2d, axis=1)
print(flipped_cols)
# Output:
# [[3 2 1]
#  [6 5 4]
#  [9 8 7]]


[[7 8 9]
 [4 5 6]
 [1 2 3]]
[[3 2 1]
 [6 5 4]
 [9 8 7]]


3. Using np.flipud() and np.fliplr()

np.flipud(): Flips an array vertically (up to down) for any 2D array.

np.fliplr(): Flips an array horizontally (left to right) for any 2D array.

Example for 2D Array

In [ ]:
# Flip vertically
flipped_ud = np.flipud(arr_2d)
print(flipped_ud)
# Output:
# [[7 8 9]
#  [4 5 6]
#  [1 2 3]]

# Flip horizontally
flipped_lr = np.fliplr(arr_2d)
print(flipped_lr)
# Output:
# [[3 2 1]
#  [6 5 4]
#  [9 8 7]]


[[7 8 9]
 [4 5 6]
 [1 2 3]]
[[3 2 1]
 [6 5 4]
 [9 8 7]]


Q 4.How can you determine the data type of elements in a NumPy array?Discuss the importance of Data types in memory mangemaent and performance.

Ans:-

You can determine the data type of elements in a NumPy array using the .dtype attribute. Here’s how it works and why data types are crucial in NumPy for memory management and performance:

Checking Data Type in a NumPy Array

In [ ]:
import numpy as np

# Creating an array
arr = np.array([1, 2, 3, 4.5])

# Checking data type of elements
print(arr.dtype)  # Output: float64 (or another type based on input elements)


float64


Importance of Data Types in Memory Management and Performance

1.Memory Management:


Fixed Memory Allocation: NumPy arrays store elements with a fixed data type, meaning each element takes up a predictable amount of memory. This predictability reduces the need for memory reallocation and enables efficient storage of large datasets.


Customizable Precision: You can specify data types like int32, float64, or complex128 based on the precision required, allowing you to optimize memory usage. For example, using int8 for small integer data reduces memory requirements compared to int64.


In [ ]:
arr_int8 = np.array([1, 2, 3], dtype=np.int8)
print(arr_int8.nbytes)  # Uses less memory than int32 or int64


3


2.Performance:

Faster Operations: Fixed-type arrays are stored as contiguous memory blocks, allowing for faster access and element-wise operations. For example, operations on float32 are faster than float64 due to lower precision.
Vectorization: NumPy's vectorized operations leverage low-level optimizations, but these depend on data types. Operations on single-precision (float32) arrays, for example, can be faster than double-precision (float64) because of the reduced data size.

3.Interoperability with External Libraries:

Many libraries for scientific computing, like TensorFlow and Pandas, integrate smoothly with NumPy and expect specific data types for optimal performance and compatibility.
In summary, data types in NumPy enable efficient memory usage and boost computational performance, especially in scientific computing and data analysis, where large datasets and fast processing are crucial. Choosing the correct data type based on your needs can help maximize both performance and memory efficiency.

Q 5.Define ndarrays in NumPy and explain their key features.How do they differ from standard Python lists?

Ans:-

In NumPy, an `ndarray` (n-dimensional array) is the core data structure that represents a grid of values, all of the same data type, and indexed by a tuple of non-negative integers. Unlike standard Python lists, which can hold elements of different data types and have more flexible structures, `ndarrays` are optimized for numerical and scientific computing.

### Key Features of `ndarrays`

1. **Homogeneous Data Types**: All elements in an `ndarray` must have the same data type (e.g., `int32`, `float64`), which allows for memory efficiency and faster computations.

2. **N-Dimensional Structure**: An `ndarray` can represent arrays of any dimension, from 1D vectors to 2D matrices to higher-dimensional tensors (e.g., 3D, 4D arrays). This makes it versatile for handling complex datasets in scientific applications.

3. **Contiguous Memory Layout**: Unlike Python lists, `ndarrays` store elements in contiguous memory blocks, which optimizes memory usage and enables fast access.

4. **Broadcasting**: NumPy's broadcasting rules allow for arithmetic operations between arrays of different shapes without explicitly resizing or reshaping them, making mathematical operations on arrays efficient and flexible.

5. **Vectorized Operations**: NumPy supports vectorized operations on `ndarrays`, allowing element-wise operations without explicit loops. This leads to faster code execution, especially for large arrays, as operations are implemented at the low level in C.

6. **Efficient Built-In Functions**: NumPy includes a wide range of optimized functions for mathematical, statistical, and linear algebra operations on `ndarrays`. Functions like `np.sum()`, `np.mean()`, and `np.dot()` operate directly on arrays and are optimized for speed.

### Differences Between `ndarrays` and Python Lists

| Feature                    | `ndarray`                          | Python List                    |
|----------------------------|------------------------------------|--------------------------------|
| **Data Type**              | Homogeneous (single data type)    | Heterogeneous (mixed data types) |
| **Memory Layout**          | Contiguous memory                 | Pointers to individual objects |
| **Dimensions**             | N-dimensional                     | 1-dimensional (can nest lists to mimic) |
| **Element-wise Operations**| Vectorized, fast                  | Requires explicit loops       |
| **Built-In Mathematical Functions** | Extensive support, optimized | Limited or requires importing math libraries |
| **Broadcasting**           | Supported                         | Not supported                 |

### Example Comparison








In [ ]:
import numpy as np

# NumPy ndarray
arr = np.array([1, 2, 3, 4])
print(arr * 2)  # Output: [2 4 6 8] - element-wise multiplication

# Python list
lst = [1, 2, 3, 4]
print(lst * 2)  # Output: [1, 2, 3, 4, 1, 2, 3, 4] - replicates list instead of element-wise operation


[2 4 6 8]
[1, 2, 3, 4, 1, 2, 3, 4]


Q 6.Analyze the performance banefits of NumPy aarays over Python lists for large-scale numerical opeations.

Ans:-

NumPy arrays (ndarrays) offer significant performance benefits over Python lists for large-scale numerical operations. These benefits stem from efficient memory handling, fast data processing, and vectorized operations that avoid the need for slow Python loops. Here’s a detailed analysis of these performance advantages:

1. Memory Efficiency
Fixed Data Types: NumPy arrays store elements with a fixed data type, while Python lists can hold objects of different types. This uniformity allows NumPy to allocate a continuous block of memory for the entire array, saving space and speeding up data access.

Compact Storage: NumPy stores data more compactly than lists. For example, a float64 NumPy array requires 8 bytes per element, whereas a Python list holding floats also includes metadata for each element, resulting in higher memory usage.

Example

In [ ]:
import numpy as np
import sys

# Python list
py_list = [i for i in range(1000000)]
print(f"Memory used by Python list: {sys.getsizeof(py_list)} bytes")

# NumPy array
np_array = np.array(py_list, dtype=np.int32)
print(f"Memory used by NumPy array: {np_array.nbytes} bytes")


Memory used by Python list: 8448728 bytes
Memory used by NumPy array: 4000000 bytes


2. Vectorized Operations:-

Element-wise Computation: NumPy performs operations on entire arrays at once (vectorization) rather than looping through elements one by one. This eliminates Python’s overhead for loops, leading to significantly faster computation.

Low-Level Implementation: Many operations in NumPy are implemented in C and optimized for performance, leveraging fast low-level libraries like BLAS and LAPACK.
Example

In [ ]:
# Multiplying each element by 2 using NumPy array
arr = np.array([1, 2, 3, 4])
result = arr * 2  # Vectorized operation, runs faster than a loop


3. Efficient Mathematical Functions:-

NumPy includes optimized built-in functions (like np.sum, np.mean, etc.) that can perform complex computations faster than Python’s built-in functions. These functions are optimized for ndarrays, taking advantage of low-level optimizations and parallelism where possible.

Example

In [ ]:
# Summing a million-element array
large_arr = np.random.rand(1000000)
%timeit np.sum(large_arr)  # Uses optimized C-implementation under the hood


341 µs ± 10.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


4. Broadcasting Capabilities:-

Broadcasting allows NumPy to perform arithmetic operations on arrays of different shapes without explicit loops. It can replicate smaller arrays across larger ones, simplifying code and increasing efficiency.

Example

In [ ]:
# Adding a scalar to each element in an array
large_arr = np.arange(1000000)
result = large_arr + 5  # Broadcasting enables fast element-wise addition


5. Parallel Processing:-

Although not inherently parallel, NumPy leverages optimized, multithreaded libraries for many operations, especially on large arrays, which can take advantage of multiple CPU cores.

Performance Comparison: NumPy Array vs. Python List
Here’s a quick example comparing the execution speed of an operation on a large NumPy array vs. a Python list:

In [ ]:
import time

# Python list multiplication
py_list = [i for i in range(1000000)]
start = time.time()
py_list_result = [x * 2 for x in py_list]
print("Python list time:", time.time() - start)

# NumPy array multiplication
np_array = np.array(py_list)
start = time.time()
np_array_result = np_array * 2  # Vectorized operation
print("NumPy array time:", time.time() - start)


Python list time: 0.09237241744995117
NumPy array time: 0.003398895263671875


Summary of Performance Benefits:-

1.Lower Memory Usage: NumPy arrays require less memory than Python lists, which is critical for large datasets.

2.Faster Computations: Vectorized operations in NumPy reduce the need for Python loops, offering significant speed improvements.

3.Efficient Built-in Functions: NumPy’s math functions are highly optimized, outperforming standard Python functions.

4.Broadcasting: Supports complex operations on differently shaped arrays without additional memory allocation or loops.

In large-scale numerical operations, these benefits make NumPy arrays vastly superior to Python lists in terms of both memory efficiency and computation speed.

Q 7.Compare vsatack() and hstack() functions in NumPy.Provide examples demonstrating their usage and output.

Ans:-

In NumPy, the vstack() and hstack() functions are used to stack arrays along different axes. Here’s a comparison of these two functions, including usage examples to demonstrate how they work:

1. np.vstack()
Purpose: Stacks arrays vertically (row-wise). The arrays are stacked along the first axis (axis=0), which means they are added as new rows.
Requirements: The arrays being stacked must have the same number of columns (second dimension) but can have different numbers of rows.
Example


In [ ]:
import numpy as np

# Define two 2D arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# Stack them vertically
vstacked = np.vstack((arr1, arr2))
print(vstacked)


[[1 2]
 [3 4]
 [5 6]
 [7 8]]


n this example, np.vstack() stacks arr1 and arr2 one on top of the other, creating a 4x2 array.

2.np.hstack()

Purpose: Stacks arrays horizontally (column-wise). The arrays are stacked along the second axis (axis=1), which means they are added as new columns.

Requirements: The arrays being stacked must have the same number of rows (first dimension) but can have different numbers of columns.
Example

In [ ]:
# Define two 2D arrays
arr3 = np.array([[1, 2], [3, 4]])
arr4 = np.array([[5, 6], [7, 8]])

# Stack them horizontally
hstacked = np.hstack((arr3, arr4))
print(hstacked)


[[1 2 5 6]
 [3 4 7 8]]


In this example, np.hstack() stacks arr3 and arr4 side by side, creating a 2x4 array.

Key Differences Between vstack() and hstack()
Feature	np.vstack()	np.hstack()
Direction	Vertical stacking (row-wise)	Horizontal stacking (column-wise)
Axis	Stacks along axis 0 (first dimension)	Stacks along axis 1 (second dimension)
Requirements	Same number of columns	Same number of rows
Additional Examples with 1D Arrays

In NumPy, the `vstack()` and `hstack()` functions are used to stack arrays along different axes. Here’s a comparison of these two functions, including usage examples to demonstrate how they work:

### 1. `np.vstack()`

- **Purpose**: Stacks arrays vertically (row-wise). The arrays are stacked along the first axis (axis=0), which means they are added as new rows.
- **Requirements**: The arrays being stacked must have the same number of columns (second dimension) but can have different numbers of rows.

#### Example
```python
import numpy as np

# Define two 2D arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# Stack them vertically
vstacked = np.vstack((arr1, arr2))
print(vstacked)
```

**Output**:
```
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
```

In this example, `np.vstack()` stacks `arr1` and `arr2` one on top of the other, creating a 4x2 array.

### 2. `np.hstack()`

- **Purpose**: Stacks arrays horizontally (column-wise). The arrays are stacked along the second axis (axis=1), which means they are added as new columns.
- **Requirements**: The arrays being stacked must have the same number of rows (first dimension) but can have different numbers of columns.

#### Example
```python
# Define two 2D arrays
arr3 = np.array([[1, 2], [3, 4]])
arr4 = np.array([[5, 6], [7, 8]])

# Stack them horizontally
hstacked = np.hstack((arr3, arr4))
print(hstacked)
```

**Output**:
```
[[1 2 5 6]
 [3 4 7 8]]
```

In this example, `np.hstack()` stacks `arr3` and `arr4` side by side, creating a 2x4 array.

### Key Differences Between `vstack()` and `hstack()`

| Feature            | `np.vstack()`                             | `np.hstack()`                            |
|--------------------|-------------------------------------------|------------------------------------------|
| **Direction**      | Vertical stacking (row-wise)              | Horizontal stacking (column-wise)        |
| **Axis**           | Stacks along axis 0 (first dimension)     | Stacks along axis 1 (second dimension)   |
| **Requirements**   | Same number of columns                    | Same number of rows                      |

### Additional Examples with 1D Arrays

Both `vstack()` and `hstack()` work with 1D arrays, though the results differ:

```python
# Define two 1D arrays
arr1d_1 = np.array([1, 2, 3])
arr1d_2 = np.array([4, 5, 6])

# Vertical stacking creates a 2D array
vstacked_1d = np.vstack((arr1d_1, arr1d_2))
print(vstacked_1d)
```

**Output**:
```
[[1 2 3]
 [4 5 6]]
```

```python
# Horizontal stacking creates a single 1D array
hstacked_1d = np.hstack((arr1d_1, arr1d_2))
print(hstacked_1d)
```

**Output**:
```
[1 2 3 4 5 6]
```

### Summary

- **`np.vstack()`**: Stacks arrays vertically, creating new rows.
- **`np.hstack()`**: Stacks arrays horizontally, creating new columns.

Choose `vstack()` for row-wise stacking and `hstack()` for column-wise stacking, depending on how you need to combine your arrays.

Q 8.Explain the difference between fliplr() and flipud() methods in NumPy,including their effects on various array dimenstions.

Ans:-

In NumPy, `fliplr()` and `flipud()` are methods used to flip arrays, but they operate along different dimensions. Here’s a breakdown of how they work and the effects on arrays of various dimensions:

### 1. `np.fliplr()`

- **Purpose**: `fliplr()` flips an array **left to right** (horizontally), reversing the order of the columns.
- **Usage**: It’s intended for 2D arrays or higher dimensions. For 1D arrays, it has no effect, as it only flips along the second axis (`axis=1`).

#### Effect on Arrays:
- **2D Array**: Reverses the order of columns.
- **3D Array**: Reverses columns across each 2D slice along the first dimension.

#### Example:
```python
import numpy as np

# 2D Array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

flipped_lr = np.fliplr(arr_2d)
print(flipped_lr)
```

**Output**:
```
[[3 2 1]
 [6 5 4]
 [9 8 7]]
```

### 2. `np.flipud()`

- **Purpose**: `flipud()` flips an array **up to down** (vertically), reversing the order of the rows.
- **Usage**: It flips along the first axis (`axis=0`), so it’s applicable to 2D arrays or higher. It has no effect on 1D arrays.

#### Effect on Arrays:
- **2D Array**: Reverses the order of rows.
- **3D Array**: Reverses rows within each 2D slice along the second dimension.

#### Example:
```python
# 2D Array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

flipped_ud = np.flipud(arr_2d)
print(flipped_ud)
```

**Output**:
```
[[7 8 9]
 [4 5 6]
 [1 2 3]]
```

### Differences Between `fliplr()` and `flipud()`

| Feature                | `np.fliplr()`                                | `np.flipud()`                                |
|------------------------|----------------------------------------------|----------------------------------------------|
| **Direction of Flip**  | Left to right (horizontal)                   | Up to down (vertical)                        |
| **Axis of Operation**  | Flips along axis 1                           | Flips along axis 0                           |
| **2D Array Effect**    | Reverses column order                        | Reverses row order                           |
| **3D Array Effect**    | Reverses columns within each 2D slice        | Reverses rows within each 2D slice           |

### Example with a 3D Array

```python
# 3D Array
arr_3d = np.array([[[1, 2], [3, 4]],
                   [[5, 6], [7, 8]],
                   [[9, 10], [11, 12]]])

# Flip left to right
flipped_3d_lr = np.fliplr(arr_3d)
print("fliplr() on 3D array:\n", flipped_3d_lr)

# Flip up to down
flipped_3d_ud = np.flipud(arr_3d)
print("flipud() on 3D array:\n", flipped_3d_ud)
```

In summary:
- **`np.fliplr()`** flips arrays horizontally by reversing column order.
- **`np.flipud()`** flips arrays vertically by reversing row order.

Choose `fliplr()` for horizontal flips and `flipud()` for vertical flips based on how you need to manipulate the array's orientation.





Q 9.Discuss the functionality of the array_spilt() method in NumPy.How does it handle uneven spilts?

Ans:-

The `numpy.array_split()` method in NumPy is used to split an array into multiple sub-arrays along a specified axis. It is particularly useful for dividing large datasets into smaller chunks for analysis or processing. Here's an overview of its functionality, including how it handles uneven splits.

### Functionality of `numpy.array_split()`

1. **Basic Syntax**:
   ```python
   numpy.array_split(ary, indices_or_sections, axis=0)
   ```

   - **`ary`**: The input array to be split.
   - **`indices_or_sections`**: This can be either an integer (number of sections to split the array into) or a 1D array of indices at which to split.
   - **`axis`**: The axis along which to split the array (default is 0 for row-wise splitting).

2. **Return Value**:
   - The method returns a list of sub-arrays.

### Handling Uneven Splits

When the input array cannot be evenly divided into the specified number of sections, `numpy.array_split()` will handle the remainder by distributing the extra elements among the resulting sub-arrays.

- **Example with Uneven Splits**: If you have an array with 7 elements and you want to split it into 3 sections, the first two sections will have 3 elements each, and the last section will have 1 element.

### Example Usage

#### Example 1: Basic Splitting

```python
import numpy as np

# Create an array
arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Split the array into 3 parts
split_arr = np.array_split(arr, 3)
print(split_arr)
```

**Output**:
```
[array([1, 2, 3]), array([4, 5]), array([6, 7])]
```

In this example, the original array is split into 3 sub-arrays. The first sub-array contains 3 elements, and the second sub-array contains 2 elements, while the last one contains the remaining 2 elements.

#### Example 2: Splitting Along a Specific Axis

```python
# Create a 2D array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],
                   [10, 11, 12]])

# Split the 2D array into 2 parts along the first axis (row-wise)
split_2d = np.array_split(arr_2d, 2, axis=0)
print(split_2d)
```

**Output**:
```
[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]])]
```

In this case, the 2D array is split into 2 parts along the rows, each containing 2 rows.

### Summary of Key Points

- **Flexible Splitting**: `numpy.array_split()` allows you to split arrays into any number of sections, even if the array size is not perfectly divisible by that number.
- **Returns Lists**: It returns a list of sub-arrays rather than a single array.
- **Handles Uneven Splits**: When the array size cannot be evenly divided, it distributes the remaining elements among the sub-arrays as evenly as possible.

In summary, `numpy.array_split()` is a versatile method for dividing arrays into smaller sub-arrays, providing a robust solution for managing data in different formats and sizes.

Q 10.Explain the concepts of vectorization and broadcasting in NumPy.How do they contribute to efficient array operations?

Ans:-

Vectorization and broadcasting are two fundamental concepts in NumPy that greatly enhance the efficiency and performance of array operations. Here’s a detailed explanation of each concept and how they contribute to efficient computations.

### Vectorization

**Definition**:
Vectorization is the process of applying operations to entire arrays (or large chunks of data) rather than iterating over individual elements. In NumPy, this means that mathematical operations are applied to entire arrays without the need for explicit loops in Python.

**Benefits**:
1. **Performance**: Vectorized operations are typically implemented in C and optimized for performance, which makes them significantly faster than Python loops.
2. **Simplicity**: Vectorized code is often more concise and easier to read than equivalent code using loops.
3. **Automatic Parallelism**: Many NumPy functions are optimized to take advantage of multiple CPU cores, allowing for more efficient processing.

**Example**:
```python
import numpy as np

# Create two large arrays
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

# Vectorized addition
result = a + b
print(result)
```

**Output**:
```
[11 22 33 44 55]
```

In this example, the addition operation is applied to the entire arrays `a` and `b` at once, resulting in a new array `result`. This is done without explicit loops.

### Broadcasting

**Definition**:
Broadcasting is a powerful mechanism that allows NumPy to perform arithmetic operations on arrays of different shapes and sizes. It automatically expands the smaller array across the larger array to make their shapes compatible for element-wise operations.

**How it Works**:
1. **Dimension Alignment**: When performing operations on two arrays, NumPy aligns the dimensions from the last dimension backwards. If the dimensions of the two arrays do not match, NumPy will try to "broadcast" the smaller array to match the larger array's shape.
2. **Expansion Rules**: Broadcasting follows a set of rules:
   - If the arrays have different numbers of dimensions, the shape of the smaller array is padded with ones on the left.
   - If the sizes of the dimensions are different, the array with size 1 is stretched to match the size of the other array.
   - If the sizes are not compatible (and neither is 1), an error is raised.

**Example**:
```python
# Create a 2D array
a = np.array([[1, 2, 3],
              [4, 5, 6]])

# Create a 1D array
b = np.array([10, 20, 30])

# Broadcasting
result = a + b  # The 1D array is broadcast across the rows of the 2D array
print(result)
```

**Output**:
```
[[11 22 33]
 [14 25 36]]
```

In this example, the 1D array `b` is broadcast to match the shape of the 2D array `a`, allowing for element-wise addition.

### Contribution to Efficient Array Operations

1. **Reduced Need for Loops**: Both vectorization and broadcasting eliminate the need for explicit loops in many cases, which can be slow in Python. This leads to cleaner and more efficient code.
   
2. **Optimized Performance**: Operations in NumPy are often implemented in optimized low-level libraries (like BLAS), making them much faster than native Python loops. Vectorized operations utilize these optimizations directly.
   
3. **Memory Efficiency**: Broadcasting allows operations on arrays of different shapes without creating large temporary arrays, conserving memory and reducing overhead.
   
4. **Conciseness and Clarity**: Code written with vectorization and broadcasting is usually more concise and easier to understand, making it easier for developers to read and maintain.

### Summary

- **Vectorization** allows for efficient array operations by applying functions to entire arrays without loops.
- **Broadcasting** enables operations between arrays of different shapes by automatically expanding the smaller array to match the size of the larger one.

Together, these features make NumPy a powerful library for numerical computing and data analysis, allowing for high-performance and concise array manipulations.


                                                             **Practical Questions**

Q 1.Create a 3*3 NumPy array with random integers between 1 and 100.Then,interchange its rows and columns.

In [ ]:
import numpy as np
N=8
rand_vals = np.random.randint(1,101, size=(N,N))
print(rand_vals)

[[ 3  6 92 35 72 70 26 36]
 [57 69 25 77 70 85 44 71]
 [87 29 93 36 59 33 48 96]
 [ 8 79 76 23 43 73  5 18]
 [27 10 25 42 26 28 14 29]
 [ 9  6 71  5 68  7 83 90]
 [38 42 89 93 33 37  9  7]
 [45 17  3 90 98 77 46 52]]


Q 2.Generate a 1D NumPy array with 10 elements.Reshape it into a 2 * 5 array,then into a 5 * 2 array.

In [2]:
import numpy as np

# Create a 1D NumPy array with 10 elements
array_1d = np.arange(10)

# Reshape into a 2x5 array
array_2x5 = array_1d.reshape(2, 5)

# Reshape into a 5x2 array
array_5x2 = array_1d.reshape(5, 2)

print("1D Array:")
print(array_1d)
print("\n2x5 Array:")
print(array_2x5)
print("\n5x2 Array:")
print(array_5x2)


1D Array:
[0 1 2 3 4 5 6 7 8 9]

2x5 Array:
[[0 1 2 3 4]
 [5 6 7 8 9]]

5x2 Array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


Q 3.Create a 4 * 4 NumPy array with random float values.Add a border of zeros around it,resulting in a 6*6 array.

In [3]:
import numpy as np

# Create a 4x4 array with random float values
array_4x4 = np.random.rand(4, 4)

# Add a border of zeros around the 4x4 array to create a 6x6 array
array_6x6 = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)

print("4x4 Array with Random Float Values:")
print(array_4x4)
print("\n6x6 Array with Zero Border:")
print(array_6x6)


4x4 Array with Random Float Values:
[[0.93695376 0.43963266 0.35172912 0.55567749]
 [0.79431684 0.8469596  0.15365318 0.29359722]
 [0.13465158 0.54109896 0.79524988 0.99068396]
 [0.04486357 0.33168489 0.76109362 0.21552673]]

6x6 Array with Zero Border:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.93695376 0.43963266 0.35172912 0.55567749 0.        ]
 [0.         0.79431684 0.8469596  0.15365318 0.29359722 0.        ]
 [0.         0.13465158 0.54109896 0.79524988 0.99068396 0.        ]
 [0.         0.04486357 0.33168489 0.76109362 0.21552673 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


Q 4.Using NumPy,create an array of integers from 10 to 60 with a step of 5.

In [4]:
import numpy as np

# Create an array of integers from 10 to 60 with a step of 5
array = np.arange(10, 65, 5)

print("Array of integers from 10 to 60 with a step of 5:")
print(array)


Array of integers from 10 to 60 with a step of 5:
[10 15 20 25 30 35 40 45 50 55 60]


Q 5.Create a NumPy array of strings ['python','numpy','pandas'].Apply different case transformations(uppercase,lowercase,title case,etc.) to each element.

In [5]:
import numpy as np

# Create a NumPy array of strings
array = np.array(['python', 'numpy', 'pandas'])

# Convert each element to uppercase
uppercase_array = np.char.upper(array)

# Convert each element to lowercase
lowercase_array = np.char.lower(array)

# Convert each element to title case
titlecase_array = np.char.title(array)

print("Original Array:")
print(array)
print("\nUppercase Array:")
print(uppercase_array)
print("\nLowercase Array:")
print(lowercase_array)
print("\nTitle Case Array:")
print(titlecase_array)


Original Array:
['python' 'numpy' 'pandas']

Uppercase Array:
['PYTHON' 'NUMPY' 'PANDAS']

Lowercase Array:
['python' 'numpy' 'pandas']

Title Case Array:
['Python' 'Numpy' 'Pandas']


Q 6.Generate a NumPy array of words.Insert a space between each character of every word in the array.

In [6]:
import numpy as np

# Create a NumPy array of words
words_array = np.array(['hello', 'world', 'numpy'])

# Insert a space between each character of every word
spaced_array = np.char.join(' ', words_array)

print("Original Array:")
print(words_array)
print("\nArray with Spaces Between Characters:")
print(spaced_array)


Original Array:
['hello' 'world' 'numpy']

Array with Spaces Between Characters:
['h e l l o' 'w o r l d' 'n u m p y']


Q 7.Create two 2D NumPy arrays and perform element-wise addition,subtraction,multipication,and division.

In [7]:
import numpy as np

# Create two 2D NumPy arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

# Perform element-wise addition
addition = np.add(array1, array2)

# Perform element-wise subtraction
subtraction = np.subtract(array1, array2)

# Perform element-wise multiplication
multiplication = np.multiply(array1, array2)

# Perform element-wise division
division = np.divide(array1, array2)

print("Array 1:")
print(array1)
print("\nArray 2:")
print(array2)
print("\nElement-wise Addition:")
print(addition)
print("\nElement-wise Subtraction:")
print(subtraction)
print("\nElement-wise Multiplication:")
print(multiplication)
print("\nElement-wise Division:")
print(division)


Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[[ 7  8  9]
 [10 11 12]]

Element-wise Addition:
[[ 8 10 12]
 [14 16 18]]

Element-wise Subtraction:
[[-6 -6 -6]
 [-6 -6 -6]]

Element-wise Multiplication:
[[ 7 16 27]
 [40 55 72]]

Element-wise Division:
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


Q 8.Use NumPy to crreate a 5*5 identity matrix,then extract its diagonal elements.

In [8]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Extract the diagonal elements
diagonal_elements = np.diag(identity_matrix)

print("5x5 Identity Matrix:")
print(identity_matrix)
print("\nDiagonal Elements:")
print(diagonal_elements)


5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements:
[1. 1. 1. 1. 1.]


Q 9.Generate a NumPy array of 100 random integers between 0 and 1000.Find and display all prime numbers in this array.

In [9]:
import numpy as np

# Function to check if a number is prime
def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

# Generate a NumPy array of 100 random integers between 0 and 1000
random_integers = np.random.randint(0, 1001, 100)

# Find all prime numbers in the array
prime_numbers = [num for num in random_integers if is_prime(num)]

print("Random Integers Array:")
print(random_integers)
print("\nPrime Numbers in the Array:")
print(prime_numbers)


Random Integers Array:
[845 259 775 579 390 469 724 121 802  24  92 484 596 100 847 696 409 772
 933 513 491 967 800 342 258 810 202 469 620 825 574 987 568 510  16 456
 767 765 305 668 889  45 541 911 811 206 435   2 575 658 155 873  76 572
 196 190  27 870 772 867 481 380  71 211 920 491 471 295 387  65 386 532
 858 649 933 465 220  51 218 967 864 835 512 432 167 123 681 882 358 359
  91 908 915 648 671 823 683 419 290 719]

Prime Numbers in the Array:
[409, 491, 967, 541, 911, 811, 2, 71, 211, 491, 967, 167, 359, 823, 683, 419, 719]


Q 10.Create a NumPy array representing daily temperatures for a month.Calculate and display the weekly averages.

In [10]:
import numpy as np

# Generate a NumPy array representing daily temperatures for 30 days
daily_temperatures = np.random.randint(20, 40, size=30)  # Random temperatures between 20 and 40

# Calculate the weekly averages
weekly_averages = [np.mean(daily_temperatures[i:i+7]) for i in range(0, 30, 7)]

print("Daily Temperatures for a Month:")
print(daily_temperatures)
print("\nWeekly Averages:")
print(weekly_averages)


Daily Temperatures for a Month:
[31 21 32 26 24 22 27 30 20 21 20 39 24 25 21 24 21 26 25 26 38 36 35 33
 29 25 28 21 20 31]

Weekly Averages:
[26.142857142857142, 25.571428571428573, 25.857142857142858, 29.571428571428573, 25.5]
